name: 'dbt_echo'

config-version: 2
version: '1.0.0'

profile: 'dbt_echo'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_echo:
    staging:
      +materialized: incremental
